// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: account_service.proto

package grpcService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateAccountRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UserData      map[string]*structpb.Value `protobuf:"bytes,1,rep,name=userData,proto3" json:"userData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccountRequest) Reset() {
	*x = ValidateAccountRequest{}
	mi := &file_account_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccountRequest) ProtoMessage() {}

func (x *ValidateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccountRequest.ProtoReflect.Descriptor instead.
func (*ValidateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateAccountRequest) GetUserData() map[string]*structpb.Value {
	if x != nil {
		return x.UserData
	}
	return nil
}

type ValidateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateAccountResponse) Reset() {
	*x = ValidateAccountResponse{}
	mi := &file_account_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateAccountResponse) ProtoMessage() {}

func (x *ValidateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateAccountResponse.ProtoReflect.Descriptor instead.
func (*ValidateAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateAccountResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetAccountByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByEmailRequest) Reset() {
	*x = GetAccountByEmailRequest{}
	mi := &file_account_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByEmailRequest) ProtoMessage() {}

func (x *GetAccountByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByEmailRequest) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetAccountByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByIdRequest) Reset() {
	*x = GetAccountByIdRequest{}
	mi := &file_account_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIdRequest) ProtoMessage() {}

func (x *GetAccountByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByIdRequest) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountByIdRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*GetAccountResponse_Account
	//	*GetAccountResponse_Error
	Result        isGetAccountResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_account_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountResponse) GetResult() isGetAccountResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetAccountResponse) GetAccount() *GetAccountResponse_AccountWrapper {
	if x != nil {
		if x, ok := x.Result.(*GetAccountResponse_Account); ok {
			return x.Account
		}
	}
	return nil
}

func (x *GetAccountResponse) GetError() *Error {
	if x != nil {
		if x, ok := x.Result.(*GetAccountResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isGetAccountResponse_Result interface {
	isGetAccountResponse_Result()
}

type GetAccountResponse_Account struct {
	Account *GetAccountResponse_AccountWrapper `protobuf:"bytes,1,opt,name=account,proto3,oneof"`
}

type GetAccountResponse_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*GetAccountResponse_Account) isGetAccountResponse_Result() {}

func (*GetAccountResponse_Error) isGetAccountResponse_Result() {}

type CreateAccountRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UserData      map[string]*structpb.Value `protobuf:"bytes,1,rep,name=userData,proto3" json:"userData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_account_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccountRequest) GetUserData() map[string]*structpb.Value {
	if x != nil {
		return x.UserData
	}
	return nil
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_account_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAccountResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetAccountResponse_AccountWrapper struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UserData      map[string]*structpb.Value `protobuf:"bytes,1,rep,name=userData,proto3" json:"userData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse_AccountWrapper) Reset() {
	*x = GetAccountResponse_AccountWrapper{}
	mi := &file_account_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse_AccountWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse_AccountWrapper) ProtoMessage() {}

func (x *GetAccountResponse_AccountWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse_AccountWrapper.ProtoReflect.Descriptor instead.
func (*GetAccountResponse_AccountWrapper) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{4, 0}
}

func (x *GetAccountResponse_AccountWrapper) GetUserData() map[string]*structpb.Value {
	if x != nil {
		return x.UserData
	}
	return nil
}

var File_account_service_proto protoreflect.FileDescriptor

const file_account_service_proto_rawDesc = "" +
	"\n" +
	"\x15account_service.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\verror.proto\"\xb0\x01\n" +
	"\x16ValidateAccountRequest\x12A\n" +
	"\buserData\x18\x01 \x03(\v2%.ValidateAccountRequest.UserDataEntryR\buserData\x1aS\n" +
	"\rUserDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"F\n" +
	"\x17ValidateAccountResponse\x12!\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"0\n" +
	"\x18GetAccountByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"5\n" +
	"\x15GetAccountByIdRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\tR\taccountId\"\xb4\x02\n" +
	"\x12GetAccountResponse\x12>\n" +
	"\aaccount\x18\x01 \x01(\v2\".GetAccountResponse.AccountWrapperH\x00R\aaccount\x12\x1e\n" +
	"\x05error\x18\x02 \x01(\v2\x06.ErrorH\x00R\x05error\x1a\xb3\x01\n" +
	"\x0eAccountWrapper\x12L\n" +
	"\buserData\x18\x01 \x03(\v20.GetAccountResponse.AccountWrapper.UserDataEntryR\buserData\x1aS\n" +
	"\rUserDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\b\n" +
	"\x06result\"\xac\x01\n" +
	"\x14CreateAccountRequest\x12?\n" +
	"\buserData\x18\x01 \x03(\v2#.CreateAccountRequest.UserDataEntryR\buserData\x1aS\n" +
	"\rUserDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"D\n" +
	"\x15CreateAccountResponse\x12!\n" +
	"\x05error\x18\x01 \x01(\v2\x06.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xa6\x02\n" +
	"\x0eAccountService\x12@\n" +
	"\rcreateAccount\x12\x15.CreateAccountRequest\x1a\x16.CreateAccountResponse\"\x00\x12E\n" +
	"\x11getAccountByEmail\x12\x19.GetAccountByEmailRequest\x1a\x13.GetAccountResponse\"\x00\x12?\n" +
	"\x0egetAccountById\x12\x16.GetAccountByIdRequest\x1a\x13.GetAccountResponse\"\x00\x12J\n" +
	"\x13validateAccountData\x12\x17.ValidateAccountRequest\x1a\x18.ValidateAccountResponse\"\x00B\x1dZ\x1buserMicro/internal/api/grpcb\x06proto3"

var (
	file_account_service_proto_rawDescOnce sync.Once
	file_account_service_proto_rawDescData []byte
)

func file_account_service_proto_rawDescGZIP() []byte {
	file_account_service_proto_rawDescOnce.Do(func() {
		file_account_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_service_proto_rawDesc), len(file_account_service_proto_rawDesc)))
	})
	return file_account_service_proto_rawDescData
}

var file_account_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_account_service_proto_goTypes = []any{
	(*ValidateAccountRequest)(nil),            // 0: ValidateAccountRequest
	(*ValidateAccountResponse)(nil),           // 1: ValidateAccountResponse
	(*GetAccountByEmailRequest)(nil),          // 2: GetAccountByEmailRequest
	(*GetAccountByIdRequest)(nil),             // 3: GetAccountByIdRequest
	(*GetAccountResponse)(nil),                // 4: GetAccountResponse
	(*CreateAccountRequest)(nil),              // 5: CreateAccountRequest
	(*CreateAccountResponse)(nil),             // 6: CreateAccountResponse
	nil,                                       // 7: ValidateAccountRequest.UserDataEntry
	(*GetAccountResponse_AccountWrapper)(nil), // 8: GetAccountResponse.AccountWrapper
	nil,                    // 9: GetAccountResponse.AccountWrapper.UserDataEntry
	nil,                    // 10: CreateAccountRequest.UserDataEntry
	(*Error)(nil),          // 11: Error
	(*structpb.Value)(nil), // 12: google.protobuf.Value
}
var file_account_service_proto_depIdxs = []int32{
	7,  // 0: ValidateAccountRequest.userData:type_name -> ValidateAccountRequest.UserDataEntry
	11, // 1: ValidateAccountResponse.error:type_name -> Error
	8,  // 2: GetAccountResponse.account:type_name -> GetAccountResponse.AccountWrapper
	11, // 3: GetAccountResponse.error:type_name -> Error
	10, // 4: CreateAccountRequest.userData:type_name -> CreateAccountRequest.UserDataEntry
	11, // 5: CreateAccountResponse.error:type_name -> Error
	12, // 6: ValidateAccountRequest.UserDataEntry.value:type_name -> google.protobuf.Value
	9,  // 7: GetAccountResponse.AccountWrapper.userData:type_name -> GetAccountResponse.AccountWrapper.UserDataEntry
	12, // 8: GetAccountResponse.AccountWrapper.UserDataEntry.value:type_name -> google.protobuf.Value
	12, // 9: CreateAccountRequest.UserDataEntry.value:type_name -> google.protobuf.Value
	5,  // 10: AccountService.createAccount:input_type -> CreateAccountRequest
	2,  // 11: AccountService.getAccountByEmail:input_type -> GetAccountByEmailRequest
	3,  // 12: AccountService.getAccountById:input_type -> GetAccountByIdRequest
	0,  // 13: AccountService.validateAccountData:input_type -> ValidateAccountRequest
	6,  // 14: AccountService.createAccount:output_type -> CreateAccountResponse
	4,  // 15: AccountService.getAccountByEmail:output_type -> GetAccountResponse
	4,  // 16: AccountService.getAccountById:output_type -> GetAccountResponse
	1,  // 17: AccountService.validateAccountData:output_type -> ValidateAccountResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_account_service_proto_init() }
func file_account_service_proto_init() {
	if File_account_service_proto != nil {
		return
	}
	file_error_proto_init()
	file_account_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_account_service_proto_msgTypes[4].OneofWrappers = []any{
		(*GetAccountResponse_Account)(nil),
		(*GetAccountResponse_Error)(nil),
	}
	file_account_service_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_service_proto_rawDesc), len(file_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_service_proto_goTypes,
		DependencyIndexes: file_account_service_proto_depIdxs,
		MessageInfos:      file_account_service_proto_msgTypes,
	}.Build()
	File_account_service_proto = out.File
	file_account_service_proto_goTypes = nil
	file_account_service_proto_depIdxs = nil
}
