// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: account_service.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateUserDataRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UserData      map[string]*structpb.Value `protobuf:"bytes,1,rep,name=userData,proto3" json:"userData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateUserDataRequest) Reset() {
	*x = ValidateUserDataRequest{}
	mi := &file_account_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserDataRequest) ProtoMessage() {}

func (x *ValidateUserDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserDataRequest.ProtoReflect.Descriptor instead.
func (*ValidateUserDataRequest) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateUserDataRequest) GetUserData() map[string]*structpb.Value {
	if x != nil {
		return x.UserData
	}
	return nil
}

type ValidateUserDataResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Accept         bool                   `protobuf:"varint,1,opt,name=accept,proto3" json:"accept,omitempty"`
	Error          string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	DetailedErrors []*FieldError          `protobuf:"bytes,3,rep,name=detailedErrors,proto3" json:"detailedErrors,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateUserDataResponse) Reset() {
	*x = ValidateUserDataResponse{}
	mi := &file_account_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateUserDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateUserDataResponse) ProtoMessage() {}

func (x *ValidateUserDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateUserDataResponse.ProtoReflect.Descriptor instead.
func (*ValidateUserDataResponse) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateUserDataResponse) GetAccept() bool {
	if x != nil {
		return x.Accept
	}
	return false
}

func (x *ValidateUserDataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ValidateUserDataResponse) GetDetailedErrors() []*FieldError {
	if x != nil {
		return x.DetailedErrors
	}
	return nil
}

type GetAccountInfoByEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountInfoByEmailRequest) Reset() {
	*x = GetAccountInfoByEmailRequest{}
	mi := &file_account_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountInfoByEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountInfoByEmailRequest) ProtoMessage() {}

func (x *GetAccountInfoByEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountInfoByEmailRequest.ProtoReflect.Descriptor instead.
func (*GetAccountInfoByEmailRequest) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountInfoByEmailRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetAccountByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountByIdRequest) Reset() {
	*x = GetAccountByIdRequest{}
	mi := &file_account_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountByIdRequest) ProtoMessage() {}

func (x *GetAccountByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountByIdRequest.ProtoReflect.Descriptor instead.
func (*GetAccountByIdRequest) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountByIdRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type GetAccountInfoResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UserData      map[string]*structpb.Value `protobuf:"bytes,1,rep,name=userData,proto3" json:"userData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountInfoResponse) Reset() {
	*x = GetAccountInfoResponse{}
	mi := &file_account_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountInfoResponse) ProtoMessage() {}

func (x *GetAccountInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountInfoResponse.ProtoReflect.Descriptor instead.
func (*GetAccountInfoResponse) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountInfoResponse) GetUserData() map[string]*structpb.Value {
	if x != nil {
		return x.UserData
	}
	return nil
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	UserData      map[string]*structpb.Value `protobuf:"bytes,1,rep,name=userData,proto3" json:"userData,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_account_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccountRequest) GetUserData() map[string]*structpb.Value {
	if x != nil {
		return x.UserData
	}
	return nil
}

type CreateAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*CreateAccountResponse_Success
	//	*CreateAccountResponse_Error
	Result        isCreateAccountResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_account_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{6}
}

func (x *CreateAccountResponse) GetResult() isCreateAccountResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *CreateAccountResponse) GetSuccess() *SuccessResponse {
	if x != nil {
		if x, ok := x.Result.(*CreateAccountResponse_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *CreateAccountResponse) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Result.(*CreateAccountResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isCreateAccountResponse_Result interface {
	isCreateAccountResponse_Result()
}

type CreateAccountResponse_Success struct {
	Success *SuccessResponse `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type CreateAccountResponse_Error struct {
	Error *ErrorResponse `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*CreateAccountResponse_Success) isCreateAccountResponse_Result() {}

func (*CreateAccountResponse_Error) isCreateAccountResponse_Result() {}

type SuccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuccessResponse) Reset() {
	*x = SuccessResponse{}
	mi := &file_account_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponse) ProtoMessage() {}

func (x *SuccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_account_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponse.ProtoReflect.Descriptor instead.
func (*SuccessResponse) Descriptor() ([]byte, []int) {
	return file_account_service_proto_rawDescGZIP(), []int{7}
}

func (x *SuccessResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_account_service_proto protoreflect.FileDescriptor

const file_account_service_proto_rawDesc = "" +
	"\n" +
	"\x15account_service.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\verror.proto\"\xb2\x01\n" +
	"\x17ValidateUserDataRequest\x12B\n" +
	"\buserData\x18\x01 \x03(\v2&.ValidateUserDataRequest.UserDataEntryR\buserData\x1aS\n" +
	"\rUserDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"}\n" +
	"\x18ValidateUserDataResponse\x12\x16\n" +
	"\x06accept\x18\x01 \x01(\bR\x06accept\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x123\n" +
	"\x0edetailedErrors\x18\x03 \x03(\v2\v.FieldErrorR\x0edetailedErrors\"4\n" +
	"\x1cGetAccountInfoByEmailRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"5\n" +
	"\x15GetAccountByIdRequest\x12\x1c\n" +
	"\taccountId\x18\x01 \x01(\tR\taccountId\"\xb0\x01\n" +
	"\x16GetAccountInfoResponse\x12A\n" +
	"\buserData\x18\x01 \x03(\v2%.GetAccountInfoResponse.UserDataEntryR\buserData\x1aS\n" +
	"\rUserDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"\xac\x01\n" +
	"\x14CreateAccountRequest\x12?\n" +
	"\buserData\x18\x01 \x03(\v2#.CreateAccountRequest.UserDataEntryR\buserData\x1aS\n" +
	"\rUserDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"w\n" +
	"\x15CreateAccountResponse\x12,\n" +
	"\asuccess\x18\x01 \x01(\v2\x10.SuccessResponseH\x00R\asuccess\x12&\n" +
	"\x05error\x18\x02 \x01(\v2\x0e.ErrorResponseH\x00R\x05errorB\b\n" +
	"\x06result\"+\n" +
	"\x0fSuccessResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xb5\x02\n" +
	"\x0eAccountService\x12@\n" +
	"\rcreateAccount\x12\x15.CreateAccountRequest\x1a\x16.CreateAccountResponse\"\x00\x12Q\n" +
	"\x15getAccountInfoByEmail\x12\x1d.GetAccountInfoByEmailRequest\x1a\x17.GetAccountInfoResponse\"\x00\x12C\n" +
	"\x0egetAccountById\x12\x16.GetAccountByIdRequest\x1a\x17.GetAccountInfoResponse\"\x00\x12I\n" +
	"\x10validateUserData\x12\x18.ValidateUserDataRequest\x1a\x19.ValidateUserDataResponse\"\x00B\x1dZ\x1bauthmicro/internal/api/grpcb\x06proto3"

var (
	file_account_service_proto_rawDescOnce sync.Once
	file_account_service_proto_rawDescData []byte
)

func file_account_service_proto_rawDescGZIP() []byte {
	file_account_service_proto_rawDescOnce.Do(func() {
		file_account_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_account_service_proto_rawDesc), len(file_account_service_proto_rawDesc)))
	})
	return file_account_service_proto_rawDescData
}

var file_account_service_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_account_service_proto_goTypes = []any{
	(*ValidateUserDataRequest)(nil),      // 0: ValidateUserDataRequest
	(*ValidateUserDataResponse)(nil),     // 1: ValidateUserDataResponse
	(*GetAccountInfoByEmailRequest)(nil), // 2: GetAccountInfoByEmailRequest
	(*GetAccountByIdRequest)(nil),        // 3: GetAccountByIdRequest
	(*GetAccountInfoResponse)(nil),       // 4: GetAccountInfoResponse
	(*CreateAccountRequest)(nil),         // 5: CreateAccountRequest
	(*CreateAccountResponse)(nil),        // 6: CreateAccountResponse
	(*SuccessResponse)(nil),              // 7: SuccessResponse
	nil,                                  // 8: ValidateUserDataRequest.UserDataEntry
	nil,                                  // 9: GetAccountInfoResponse.UserDataEntry
	nil,                                  // 10: CreateAccountRequest.UserDataEntry
	(*FieldError)(nil),                   // 11: FieldError
	(*ErrorResponse)(nil),                // 12: ErrorResponse
	(*structpb.Value)(nil),               // 13: google.protobuf.Value
}
var file_account_service_proto_depIdxs = []int32{
	8,  // 0: ValidateUserDataRequest.userData:type_name -> ValidateUserDataRequest.UserDataEntry
	11, // 1: ValidateUserDataResponse.detailedErrors:type_name -> FieldError
	9,  // 2: GetAccountInfoResponse.userData:type_name -> GetAccountInfoResponse.UserDataEntry
	10, // 3: CreateAccountRequest.userData:type_name -> CreateAccountRequest.UserDataEntry
	7,  // 4: CreateAccountResponse.success:type_name -> SuccessResponse
	12, // 5: CreateAccountResponse.error:type_name -> ErrorResponse
	13, // 6: ValidateUserDataRequest.UserDataEntry.value:type_name -> google.protobuf.Value
	13, // 7: GetAccountInfoResponse.UserDataEntry.value:type_name -> google.protobuf.Value
	13, // 8: CreateAccountRequest.UserDataEntry.value:type_name -> google.protobuf.Value
	5,  // 9: AccountService.createAccount:input_type -> CreateAccountRequest
	2,  // 10: AccountService.getAccountInfoByEmail:input_type -> GetAccountInfoByEmailRequest
	3,  // 11: AccountService.getAccountById:input_type -> GetAccountByIdRequest
	0,  // 12: AccountService.validateUserData:input_type -> ValidateUserDataRequest
	6,  // 13: AccountService.createAccount:output_type -> CreateAccountResponse
	4,  // 14: AccountService.getAccountInfoByEmail:output_type -> GetAccountInfoResponse
	4,  // 15: AccountService.getAccountById:output_type -> GetAccountInfoResponse
	1,  // 16: AccountService.validateUserData:output_type -> ValidateUserDataResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_account_service_proto_init() }
func file_account_service_proto_init() {
	if File_account_service_proto != nil {
		return
	}
	file_error_proto_init()
	file_account_service_proto_msgTypes[6].OneofWrappers = []any{
		(*CreateAccountResponse_Success)(nil),
		(*CreateAccountResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_account_service_proto_rawDesc), len(file_account_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_account_service_proto_goTypes,
		DependencyIndexes: file_account_service_proto_depIdxs,
		MessageInfos:      file_account_service_proto_msgTypes,
	}.Build()
	File_account_service_proto = out.File
	file_account_service_proto_goTypes = nil
	file_account_service_proto_depIdxs = nil
}
